[package]
name = "gitegylet"
version = "0.1.0"
authors = ["Foo Bar"]
edition = "2018"

[dependencies]
git2 = "0.13"
chrono = "0.4"
iced = { version = "0.1.1", features = ["canvas", "async-std", "debug"] }
iced_native = "0.2.2"
async-std = { version = "1.0", features = ["unstable"] }
